# site info
title: Elf on the Run
email:
twitter:
facebook:
year: 2017

# google_analytics: ""

# author info
author: Reasonable People
author-email:
author-twitter:
author-facebook:

# config info
markdown: kramdown
kramdown:
  input: GFM

# YAML defaults
defaults:
  -layout: page

# included with build
include: [about, get-involved, partner]

# excluded from build
exclude: [.gitignore, notes]